// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0MS9s6zqHtCUct1NmPG_CKYWe0Q5skxE',
    appId: '1:523081725972:web:c1d6587d32dc0bd69ecf01',
    messagingSenderId: '523081725972',
    projectId: 'twitter-clone-fb679',
    authDomain: 'twitter-clone-fb679.firebaseapp.com',
    storageBucket: 'twitter-clone-fb679.appspot.com',
    measurementId: 'G-L655KX24EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk38jkfEyzp3mxCYOiSor7DeTaOpqNZXc',
    appId: '1:523081725972:android:f25ce6b505a1cd029ecf01',
    messagingSenderId: '523081725972',
    projectId: 'twitter-clone-fb679',
    storageBucket: 'twitter-clone-fb679.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoavexYVptF9Wxs--TsYBlJ4owkdHlB-g',
    appId: '1:523081725972:ios:2ba71b94f43cb4029ecf01',
    messagingSenderId: '523081725972',
    projectId: 'twitter-clone-fb679',
    storageBucket: 'twitter-clone-fb679.appspot.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0MS9s6zqHtCUct1NmPG_CKYWe0Q5skxE',
    appId: '1:523081725972:web:b5c3d1ac8f1c0e999ecf01',
    messagingSenderId: '523081725972',
    projectId: 'twitter-clone-fb679',
    authDomain: 'twitter-clone-fb679.firebaseapp.com',
    storageBucket: 'twitter-clone-fb679.appspot.com',
    measurementId: 'G-GJ436YKFHP',
  );
}
